spring:
  application:
    name: fueledbychai-switchboard
  thymeleaf:
    cache: false

server:
  shutdown: graceful

switchboard:
  broadcast-interval-ms: 100
  history-minutes: 10
  max-rows: 50
  proxy:
    enabled: true
    host: "localhost"
    port: 1080
